"""
01_split_new_data.py
====================
VERSION: v1.4-combined-source
CHANGE: 
  TRAIN → from 'new data/' CSVs (Oct 2025 - Jan 1 2026, full history)
  TEST  → from 'new_raw_data/' CSVs (Jan 12-15 2026, recent data)
  Hydra → use OLD hydra from 'new_processed_data/HYDRA_TRAIN.parquet' 
          already generated by previous run (3,948 rows, Oct-Jan coverage)
          Only regenerate TEST from new data/ Hydra.
"""

import pandas as pd
import os
import gc
from pathlib import Path

TRAIN_SOURCE  = r"D:\te connectivity 3\new data"
TEST_SOURCE   = r"D:\te connectivity 3\new_raw_data"
PROCESSED_DIR = r"D:\te connectivity 3\new_processed_data"

CUTOFF_DATE = pd.to_datetime("2026-01-11 23:59:59", utc=True)

os.makedirs(PROCESSED_DIR, exist_ok=True)

# Machine ID mapping: filename stem prefix → machine_id
def get_machine_id(filename):
    return Path(filename).stem.split("-")[0].upper()


def process_train_files():
    """Read large CSVs from 'new data/' — Oct 2025 to Jan 1 2026."""
    print(f"\n{'='*60}")
    print(f"STEP 1 — TRAIN files from '{TRAIN_SOURCE}'")
    print(f"{'='*60}")

    raw_dir = Path(TRAIN_SOURCE)
    csv_files = sorted(raw_dir.glob("*.csv"))
    print(f"Found {len(csv_files)} CSV files")

    for csv_file in csv_files:
        machine_id = get_machine_id(csv_file.name)
        print(f"\n⏳ Loading {csv_file.name} ({csv_file.stat().st_size/1e6:.0f} MB)...")

        df = pd.read_csv(str(csv_file))
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

        print(f"   -> Rows: {len(df):,} | "
              f"Range: {df['timestamp'].min().date()} to {df['timestamp'].max().date()}")

        # Everything up to cutoff is TRAIN
        train_df = df[df["timestamp"] <= CUTOFF_DATE]

        out_path = os.path.join(PROCESSED_DIR, f"{machine_id}_TRAIN.parquet")
        train_df.to_parquet(out_path, index=False)

        print(f"✅ {machine_id} TRAIN: {len(train_df):,} rows saved")

        del df, train_df
        gc.collect()


def process_test_files():
    """Read smaller CSVs from 'new_raw_data/' — Jan 12-15 2026."""
    print(f"\n{'='*60}")
    print(f"STEP 2 — TEST files from '{TEST_SOURCE}'")
    print(f"{'='*60}")

    raw_dir = Path(TEST_SOURCE)
    csv_files = sorted(raw_dir.glob("*.csv"))
    print(f"Found {len(csv_files)} CSV files")

    for csv_file in csv_files:
        machine_id = get_machine_id(csv_file.name)
        print(f"\n⏳ Loading {csv_file.name} ({csv_file.stat().st_size/1e6:.0f} MB)...")

        df = pd.read_csv(str(csv_file))
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

        print(f"   -> Rows: {len(df):,} | "
              f"Range: {df['timestamp'].min().date()} to {df['timestamp'].max().date()}")

        # Everything after cutoff is TEST
        test_df = df[df["timestamp"] > CUTOFF_DATE]

        out_path = os.path.join(PROCESSED_DIR, f"{machine_id}_TEST.parquet")
        test_df.to_parquet(out_path, index=False)

        print(f"✅ {machine_id} TEST: {len(test_df):,} rows saved")

        del df, test_df
        gc.collect()


def process_hydra():
    """
    Use the already-correct HYDRA_TRAIN from previous run (old Hydra, 3948 rows).
    Generate HYDRA_TEST from new data/ Hydra for test period.
    """
    print(f"\n{'='*60}")
    print(f"STEP 3 — Hydra files")
    print(f"{'='*60}")

    # Check if old HYDRA_TRAIN already exists and has good coverage
    old_hydra_path = Path(PROCESSED_DIR) / "HYDRA_TRAIN.parquet"
    if old_hydra_path.exists():
        old = pd.read_parquet(old_hydra_path)
        old["machine_event_create_date"] = pd.to_datetime(
            old["machine_event_create_date"], utc=True, errors="coerce")
        min_date = old["machine_event_create_date"].min().date()
        max_date = old["machine_event_create_date"].max().date()
        print(f"Existing HYDRA_TRAIN: {len(old):,} rows | {min_date} to {max_date}")

        if min_date.year == 2025 and min_date.month <= 10:
            print("✅ HYDRA_TRAIN already covers Oct 2025+ — keeping it.")
        else:
            print("⚠️  HYDRA_TRAIN doesn't cover Oct 2025. Will regenerate.")
            old_hydra_path = None
    else:
        old_hydra_path = None

    # Generate HYDRA_TEST from new data/ Hydra
    new_data_dir = Path(TRAIN_SOURCE)
    xlsx_files = list(new_data_dir.glob("*.xlsx"))
    if xlsx_files:
        hydra_file = xlsx_files[0]
        print(f"\nLoading Hydra from new data/: {hydra_file.name}")
        df = pd.read_excel(str(hydra_file))
        df["machine_event_create_date"] = pd.to_datetime(
            df["machine_event_create_date"], utc=True, errors="coerce")

        test_hydra = df[df["machine_event_create_date"] > CUTOFF_DATE]
        test_path  = os.path.join(PROCESSED_DIR, "HYDRA_TEST.parquet")
        test_hydra.to_parquet(test_path, index=False)
        print(f"✅ HYDRA_TEST: {len(test_hydra):,} rows saved")

        # If no good HYDRA_TRAIN exists, save train portion too
        if old_hydra_path is None:
            train_hydra = df[df["machine_event_create_date"] <= CUTOFF_DATE]
            train_path  = os.path.join(PROCESSED_DIR, "HYDRA_TRAIN.parquet")
            train_hydra.to_parquet(train_path, index=False)
            print(f"✅ HYDRA_TRAIN: {len(train_hydra):,} rows saved")
    else:
        print("⚠️  No xlsx found in new data/ — skipping HYDRA_TEST generation")


def print_summary():
    print(f"\n{'='*60}")
    print(f"SUMMARY")
    print(f"{'='*60}")
    proc = Path(PROCESSED_DIR)
    for f in sorted(proc.glob("*.parquet")):
        df = pd.read_parquet(f)
        size_mb = f.stat().st_size / 1e6
        print(f"  {f.name}: {len(df):,} rows | {size_mb:.1f} MB")
        del df
        gc.collect()


if __name__ == "__main__":
    print("🚀 Starting Data Splitter v1.4-combined-source")
    print(f"   TRAIN source: {TRAIN_SOURCE}")
    print(f"   TEST source:  {TEST_SOURCE}")
    print(f"   Output:       {PROCESSED_DIR}")
    print(f"   Cutoff:       {CUTOFF_DATE.date()}")

    process_hydra()
    process_train_files()
    process_test_files()
    print_summary()

    print(f"\n🎉 DONE! Next steps — run in order:")
    print(f"  python scripts/02_merge_train_data.py")
    print(f"  python scripts/build_and_train_v1_2b.py")
    print(f"  python scripts/retrain_only_v1_2e.py")